"""empty message

Revision ID: 295a929a440f
Revises: e9406c44d523
Create Date: 2021-06-12 03:33:55.593018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '295a929a440f'
down_revision = 'e9406c44d523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
