version: "3.6"

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
#    command: flask run -h "0.0.0.0"
    command: python app.py
    container_name: flask-api
    env_file:
      - .env
    image: python:3.9.5
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app/
  posgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data

