version: "3.6"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    command: npm start
    container_name: node
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    restart: unless-stopped
  flask:
    build:
      context: .
      dockerfile: Dockerfile-backend
    command: flask run -h "0.0.0.0"
    container_name: flask-api
    env_file:
      - .env
    image: python:3.9.5
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./backend/:/usr/src/app/
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data
