version: "3.6"

services:
  postgres:
    image: postgres
    container_name: postgres-fsnd
    env_file:
      - .env
    hostname: postgres-fsnd
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "python", "flask_hello_app.py" ]
    container_name: flask-fsnd
    environment:
      - FLASK_PORT=5000
    image: python:3.9.5
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app/
