version: "3.6"

services:
  api_server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "app.py"]
    container_name: fyyur
    env_file:
      - .env
    image: python:3.9.5
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app/